const colors = {
  light: {
    text: "#1C2B33",
    tint: "#3A7D6B",
    background: "#F8F6F1",
    foreground: "#1C2B33",
    card: "#FFFFFF",
    cardForeground: "#1C2B33",
    primary: "#3A7D6B",
    primaryForeground: "#FFFFFF",
    secondary: "#EBF4F0",
    secondaryForeground: "#1C2B33",
    muted: "#EAE7DF",
    mutedForeground: "#8C8C9A",
    accent: "#F5A623",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDD9D1",
    input: "#E8E5DC",
    success: "#4CAF7D",
    successForeground: "#FFFFFF",
    warning: "#F5A623",
    warningForeground: "#FFFFFF",
    info: "#4A90A4",
    infoForeground: "#FFFFFF",
  },
  dark: {
    text: "#F0EEE9",
    tint: "#5BA894",
    background: "#141C22",
    foreground: "#F0EEE9",
    card: "#1E2A32",
    cardForeground: "#F0EEE9",
    primary: "#5BA894",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3330",
    secondaryForeground: "#F0EEE9",
    muted: "#232E38",
    mutedForeground: "#9A9AAA",
    accent: "#F5A623",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A3640",
    input: "#2A3640",
    success: "#4CAF7D",
    successForeground: "#FFFFFF",
    warning: "#F5A623",
    warningForeground: "#FFFFFF",
    info: "#4A90A4",
    infoForeground: "#FFFFFF",
  },
  radius: 16,
};

export default colors;
